name: bridge
main: dev.adrwas.mapbridge.MapBridge
version: 0.1
api-version: 1.16
commands:
  dir:
    description: view a directory
  createproject:
    description: create a project
  projects:
    description: list projects
  openproject:
    description: open a project